name: meyirim
description: meyirim.kz


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_page_transition: ^0.1.0
  path_provider: ^1.6.24
  intl: 0.17.0-nullsafety.2
  splashscreen: ^1.3.5
  flutter_launcher_icons: ^0.8.1
  image_res: ^0.2.3
  flutter_svg: ^0.19.1
  shared_preferences: ^0.5.12+4
  flutter_gifimage: ^1.0.1
  http: ^0.12.2
  flutter_share: ^1.0.5
  mask_text_input_formatter: ^1.2.1
  scroll_app_bar: ^1.0.2
  carousel_slider: ^2.3.1
  youtube_player_iframe: ^1.1.0
  cached_network_image: ^2.4.1
  flutter_cache_manager: ^2.0.0
  async: ^2.4.2
  connectivity: ^2.0.2
  uuid: ^2.2.2
  dio: ^3.0.10
  url_launcher: ^5.7.10
  flutter_web_browser: ^0.13.1
  mime: ^0.9.7
  firebase_core: ^0.5.3
  firebase_dynamic_links: ^0.6.3
  firebase_messaging: ^7.0.3
  directus: ^0.4.1
  validators: ^2.0.1
  flutter_localizations:
    sdk: flutter

dependency_overrides:
  json_annotation: ^3.0.1



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/logo.png
     - assets/icon/home.svg
     - assets/icon/search.svg
     - assets/icon/user.svg
     - assets/icon/check-mark.svg
     - assets/images/logo_main.png
     - assets/icon/icon.png
     - lang/kk.json
     - lang/ru.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
#  fonts:
#      - family: meyirimfontIcons
#        fonts:
#         - asset: lib/fonts/meyirimfontIcons.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
